### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [openbeats/openbeats#101]
Hi,<br><br>url : https://github.com/openbeats/openbeats/blob/c2aaea3b8fc398dcc719b44b91e58695daaff2c5/services/core/src/config/index.js <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by noelimmi** [comment]
Hi @shaybenb Thanks for reporting, We are no longer supporting this projects and thats why we haven't saved creds as encrypted. 
All the associated accounts for those creds hav already been deleted.

**Comment by noelimmi** [comment]
> Hi,
> 
> url : https://github.com/openbeats/openbeats/blob/c2aaea3b8fc398dcc719b44b91e58695daaff2c5/services/core/src/config/index.js
> 
> You have commit that need to remove from the github history
> attacker can see it and use it ...
> 
> encrypt your secrets !!!!
> 
> Our Bug Help you to be more Secure and protect your data ?
> Buy me a coffee (or more likely a beer)
> https://www.paypal.com/paypalme/bugbounty1/150USD
> https://www.buymeacoffee.com/bugbounty
> ☕☕☕☕☕

Hi @shaybenb Thanks for reporting, We are no longer supporting this projects and thats why we haven't saved creds as encrypted. 
All the associated accounts for those creds hav already been deleted.
